// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPBu7HPIxUMk7mNxczAMA6pdp3eAXoQQ',
    appId: '1:988639601997:web:e07dc4aba6b13680f98304',
    messagingSenderId: '988639601997',
    projectId: 'my-fl-notes',
    authDomain: 'my-fl-notes.firebaseapp.com',
    storageBucket: 'my-fl-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVpi2U8qIDCwj7_6laBeyQqixmmeHZAw',
    appId: '1:988639601997:android:36dc099b5912c31cf98304',
    messagingSenderId: '988639601997',
    projectId: 'my-fl-notes',
    storageBucket: 'my-fl-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATFnQlAvYpKDuPvb6sk3AbES9SCLlr44M',
    appId: '1:988639601997:ios:7e3715660bf0a7b5f98304',
    messagingSenderId: '988639601997',
    projectId: 'my-fl-notes',
    storageBucket: 'my-fl-notes.appspot.com',
    iosBundleId: 'com.hello.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATFnQlAvYpKDuPvb6sk3AbES9SCLlr44M',
    appId: '1:988639601997:ios:699afc2d46e11061f98304',
    messagingSenderId: '988639601997',
    projectId: 'my-fl-notes',
    storageBucket: 'my-fl-notes.appspot.com',
    iosBundleId: 'com.hello.mynotes.RunnerTests',
  );
}
